# Generated by Django 5.2.15 on 2026-06-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, default='', max_length=150)),
                ('message', models.TextField()),
                ('machine_interest', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('model_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('GLUING', 'Gluing Machines'), ('CARTONING', 'Cartoning Machines'), ('CARTONATOR', 'Cartonator Machines'), ('SHIPPER', 'Shipper Carton Machines')], default='GLUING', max_length=50)),
                ('image_path', models.CharField(help_text="Relative to static folder, e.g., 'images/machine1.png'", max_length=250)),
                ('features', models.JSONField(default=list, help_text="A list of bullet features, e.g., ['Timer base control', 'Auto/Manual system']")),
                ('description', models.TextField(blank=True, default='')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text="Dict of tech specs, e.g., {'speed': '30-60 pcs/min', 'power': '220V'}")),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'model_number'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('quote', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
