# Generated by Django 5.2.15 on 2026-06-21 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("background_image", models.ImageField(blank=True, null=True, upload_to="hero_sections/")),
                ("back_link_label", models.CharField(default="Back to Home", max_length=100)),
                ("back_link_url", models.CharField(default="/", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Sections",
            },
        ),
    ]
