# Generated by Django 5.2.15 on 2026-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_ctasection_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMapSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(max_length=100, unique=True)),
                ('title_prefix', models.CharField(default='Visit Our', max_length=100)),
                ('title_accent', models.CharField(default='Office', max_length=100)),
                ('description', models.CharField(default='Find us on the map', max_length=255)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='contact_maps/')),
                ('map_image_url', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Contact Map Section',
                'verbose_name_plural': 'Contact Map Sections',
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(max_length=100, unique=True)),
                ('intro_prefix', models.CharField(default='GET IN', max_length=100)),
                ('intro_accent', models.CharField(default='TOUCH', max_length=100)),
                ('intro_description', models.CharField(default="We'd love to hear from you", max_length=255)),
                ('form_title', models.CharField(default='Send us a message', max_length=200)),
                ('name_label', models.CharField(default='Name', max_length=100)),
                ('name_placeholder', models.CharField(default='Your name', max_length=100)),
                ('email_label', models.CharField(default='Email', max_length=100)),
                ('email_placeholder', models.CharField(default='your@email.com', max_length=100)),
                ('phone_label', models.CharField(default='Phone', max_length=100)),
                ('phone_placeholder', models.CharField(default='+91 00000 00000', max_length=100)),
                ('message_label', models.CharField(default='Message', max_length=100)),
                ('message_placeholder', models.CharField(default='Tell us about your requirements...', max_length=255)),
                ('button_label', models.CharField(default='Send Message', max_length=100)),
                ('address_title', models.CharField(default='Address', max_length=100)),
                ('address_line1', models.CharField(default='B5/9, 1st Floor, Paschim Vihar', max_length=200)),
                ('address_line2', models.CharField(default='New Delhi-110063', max_length=200)),
                ('phone_card_title', models.CharField(default='Phone', max_length=100)),
                ('phone_card_value', models.CharField(default='+91 97173 33206', max_length=50)),
                ('phone_card_href', models.CharField(default='tel:+919717333206', max_length=100)),
                ('email_card_title', models.CharField(default='Email', max_length=100)),
                ('email_card_value', models.CharField(default='contact@glupac.in', max_length=100)),
                ('email_card_href', models.CharField(default='mailto:contact@glupac.in', max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': 'Contact Sections',
            },
        ),
    ]
