# Generated by Django 5.2.15 on 2026-07-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_machine_video_iframe_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionVisionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(default='about', max_length=100, unique=True)),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission_description', models.TextField(default='To empower global industries with state-of-the-art, customized gluing and packaging automation. We commit to continuous technological enhancement, ensuring zero defect rates, high operator safety, and exceptional long-term machinery value.')),
                ('vision_title', models.CharField(default='Our Vision', max_length=200)),
                ('vision_description', models.TextField(default='To be internationally recognized as the benchmark of excellence in structural packaging systems. We strive to pioneer intelligence and PLC capabilities, helping modern manufacturing lines transition cleanly onto green, low-waste automated solutions.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mission & Vision Section',
                'verbose_name_plural': 'Mission & Vision Sections',
            },
        ),
    ]
