# Generated by Django 5.2.15 on 2026-07-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_missionvisionsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='industries/')),
                ('detail_image', models.ImageField(blank=True, help_text='Optional overlay image for the home page carousel.', null=True, upload_to='industries/')),
                ('bullet_points', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_home', models.BooleanField(default=True, help_text='Show this industry in the home page carousel.')),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='missionvisionsection',
            name='mission_description',
            field=models.TextField(default='To empower global industries with state-of-the-art, customized gluing and packaging automation. We commit to continuous technological enhancement, ensuring zero defect rates, high operator safety, and exceptional long-term machinery value.', help_text='Supports HTML entered through the admin rich text editor.'),
        ),
        migrations.AlterField(
            model_name='missionvisionsection',
            name='vision_description',
            field=models.TextField(default='To be internationally recognized as the benchmark of excellence in structural packaging systems. We strive to pioneer intelligence and PLC capabilities, helping modern manufacturing lines transition cleanly onto green, low-waste automated solutions.', help_text='Supports HTML entered through the admin rich text editor.'),
        ),
    ]
