# Generated by Django 5.2.15 on 2026-07-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_machine_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Supports HTML entered through the TinyMCE admin editor.'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Supports HTML entered through the TinyMCE admin editor.'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='specifications',
            field=models.TextField(blank=True, default='', help_text='Supports HTML entered through the TinyMCE admin editor.'),
        ),
        migrations.AlterField(
            model_name='missionvisionsection',
            name='mission_description',
            field=models.TextField(default='To empower global industries with state-of-the-art, customized gluing and packaging automation. We commit to continuous technological enhancement, ensuring zero defect rates, high operator safety, and exceptional long-term machinery value.', help_text='Supports HTML entered through the TinyMCE admin editor.'),
        ),
        migrations.AlterField(
            model_name='missionvisionsection',
            name='vision_description',
            field=models.TextField(default='To be internationally recognized as the benchmark of excellence in structural packaging systems. We strive to pioneer intelligence and PLC capabilities, helping modern manufacturing lines transition cleanly onto green, low-waste automated solutions.', help_text='Supports HTML entered through the TinyMCE admin editor.'),
        ),
    ]
