# Generated by Django 5.2.15 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_alter_machine_description_alter_machine_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional wide background image for this product's solution-page hero.",
                null=True,
                upload_to="products/heroes/",
            ),
        ),
    ]