# Generated by Django 5.2.14 on 2026-08-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_machine_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Product SKU ID'),
        ),
    ]
